"""initial schema

Revision ID: 7f0ed43c997e
Revises: 
Create Date: 2026-09-19 14:41:57.720657
"""
from alembic import op
import sqlalchemy as sa


revision = '7f0ed43c997e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_stores_tenant_name')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_id', sa.String(length=32), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('api_key_prefix', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cameras',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'external_id', name='uq_cameras_store_external')
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cameras_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cameras_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('count_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('camera_id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=8), nullable=False),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('schema_version', sa.SmallInteger(), nullable=False),
    sa.Column('raw_error', sa.Text(), nullable=True),
    sa.CheckConstraint("event_type IN ('enter','exit')", name='ck_count_events_type'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('count_events', schema=None) as batch_op:
        batch_op.create_index('ix_count_events_camera_ts', ['camera_id', 'event_ts'], unique=False)
        batch_op.create_index('ix_count_events_store_ts', ['store_id', 'event_ts'], unique=False)
        batch_op.create_index('ix_count_events_tenant_ts', ['tenant_id', 'event_ts'], unique=False)

    op.create_table('count_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('camera_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('ax', sa.Double(), nullable=False),
    sa.Column('ay', sa.Double(), nullable=False),
    sa.Column('bx', sa.Double(), nullable=False),
    sa.Column('by', sa.Double(), nullable=False),
    sa.Column('enter_side', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id', 'external_id', name='uq_count_lines_camera_external')
    )
    with op.batch_alter_table('count_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_count_lines_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_count_lines_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('count_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_count_lines_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_count_lines_camera_id'))

    op.drop_table('count_lines')
    with op.batch_alter_table('count_events', schema=None) as batch_op:
        batch_op.drop_index('ix_count_events_tenant_ts')
        batch_op.drop_index('ix_count_events_store_ts')
        batch_op.drop_index('ix_count_events_camera_ts')

    op.drop_table('count_events')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cameras_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cameras_store_id'))

    op.drop_table('cameras')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_devices_store_id'))

    op.drop_table('devices')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_tenant_id'))

    op.drop_table('stores')
    op.drop_table('tenants')
    # ### end Alembic commands ###
